name: display_metrics
description: Flutter plugin to retrieve device display metrics (resolution, size, PPI, diagonal). Convert inches & mm to Flutter logical pixels.
homepage: https://github.com/nukeolay/display_metrics/tree/main/display_metrics
version: 0.4.1

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  display_metrics_platform_interface: ^1.0.3
  display_metrics_android: ^1.0.2
  display_metrics_ios: ^1.0.1
  display_metrics_windows:
    path: ../display_metrics_windows
  display_metrics_web:
    path: ../display_metrics_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: display_metrics_android
      ios:
        default_package: display_metrics_ios
      windows:
        default_package: display_metrics_windows
      web:
        default_package: display_metrics_web

topics:
  - screen
  - ppi
  - size
  - resolution
  - pixels